# Generated by Django 4.1.2 on 2022-10-19 17:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Nome')),
                ('price', models.FloatField(default=0.0, verbose_name='Valor pago')),
            ],
            options={
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='Nome')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('start_date', models.DateField(verbose_name='Data da assinatura')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('plans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plano')),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
