# Generated by Django 4.1.3 on 2023-06-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plano_id_alter_subscriber_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plano',
            options={},
        ),
        migrations.RemoveField(
            model_name='plano',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='price',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='plano',
            name='duracao_dias',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano',
            name='tipo',
            field=models.CharField(choices=[('gold', 'Gold'), ('platina', 'Platina'), ('diamante', 'Diamante')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
