# Generated by Django 4.1.3 on 2022-11-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_delete_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
