# Generated by Django 4.1.3 on 2023-01-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='telefone',
            new_name='cellphone',
        ),
    ]
