# Generated by Django 4.1.3 on 2023-01-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_telefone_perfil_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cellphone',
            field=models.CharField(max_length=16, null=True, verbose_name='Celular com DDD'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='full_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome Completo'),
        ),
    ]
