# Generated by Django 4.1.2 on 2022-10-19 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentsAdress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deletado')),
                ('adress', models.CharField(max_length=50, verbose_name='Endereço')),
                ('house_number', models.CharField(max_length=5, verbose_name='Número')),
                ('complement', models.CharField(max_length=100, verbose_name='Complemento')),
                ('district', models.CharField(max_length=30, verbose_name='Bairro')),
                ('zip_code', models.CharField(max_length=8, verbose_name='CEP')),
                ('city', models.CharField(max_length=30, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='estado')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstablishmentsCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deletado')),
                ('EstablishmentsCategory', models.CharField(max_length=30, verbose_name='Categoria do estabelecimento')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstablishmentsContacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deletado')),
                ('cellphone', models.CharField(max_length=11, verbose_name='Celular com DDD')),
                ('telephone', models.CharField(blank=True, default='', max_length=8, verbose_name='Telefone')),
                ('email', models.CharField(blank=True, default='', max_length=50, verbose_name='E-mail')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstablishmentsOpeningHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deletado')),
                ('days', models.CharField(choices=[('DO', 'Domingo'), ('SG', 'Segunda-feira'), ('TE', 'Terça-feira'), ('QA', 'Quarta-feira'), ('QI', 'Quinta-feira'), ('SX', 'Sexta-feira'), ('SO', 'Sábado'), ('SS', 'Segunda a sexta'), ('SA', 'Segunda a sábado'), ('TO', 'Todos os dias')], default='Escolha', max_length=2, verbose_name='Dias da semana')),
                ('opening_time', models.TimeField(verbose_name='Abertura')),
                ('closing_time', models.TimeField(verbose_name='Fechamento')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstablishmentsProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deletado')),
                ('Establishment', models.CharField(max_length=100, verbose_name='Nome do estabelecimento')),
                ('description', models.CharField(max_length=500, verbose_name='Descreva seu estabelecimento')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
