# Generated by Django 4.1.2 on 2022-10-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_remove_establishmentsadress_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentsopeninghours',
            name='days',
            field=models.CharField(choices=[('Domingo', 'Segunda-feira'), ('Terça-feira', 'Quarta-feira'), ('Quinta-feira', 'Sexta-feira'), ('Sábado', 'Segunda a sexta'), ('Segunda a sábado', 'Todos os dias')], max_length=16, verbose_name='Dias da semana'),
        ),
    ]
