# Generated by Django 4.1.2 on 2022-10-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0003_alter_establishmentsopeninghours_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentsopeninghours',
            name='days',
            field=models.CharField(choices=[('DO', 'Domingo'), ('SG', 'Segunda-feira'), ('TE', 'Terça-feira'), ('QA', 'Quarta-feira'), ('QI', 'Quinta-feira'), ('SX', 'Sexta-feira'), ('SO', 'Sábado'), ('SS', 'Segunda a sexta'), ('SA', 'Segunda a sábado'), ('TO', 'Todos os dias')], default='Escolha', max_length=16, verbose_name='Dias da semana'),
        ),
    ]
