# Generated by Django 4.1.2 on 2022-10-19 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0004_alter_establishmentsopeninghours_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstablishmentsAdress',
        ),
        migrations.DeleteModel(
            name='EstablishmentsContacts',
        ),
        migrations.DeleteModel(
            name='EstablishmentsOpeningHours',
        ),
        migrations.RemoveField(
            model_name='establishmentscategories',
            name='EstablishmentsCategory',
        ),
        migrations.AddField(
            model_name='establishmentscategories',
            name='name',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='adress',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='establishments.establishmentscategories'),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='cellphone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular com DDD'),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Fechamento'),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='days',
            field=models.CharField(choices=[('Domingo', 'Domingo'), ('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Segunda a sexta', 'Segunda a sexta'), ('Segunda a sábado', 'Segunda a sábado'), ('Todos os dias', 'Todos os dias')], default='Escolha', max_length=16, verbose_name='Dias da semana'),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='house_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='opening_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Abertura'),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='state',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='establishmentsprofile',
            name='Establishment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do estabelecimento'),
        ),
        migrations.AlterField(
            model_name='establishmentsprofile',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descreva seu estabelecimento'),
        ),
    ]
