# Generated by Django 4.1.2 on 2022-10-19 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0005_delete_establishmentsadress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentsAdress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('adress', models.CharField(max_length=50, verbose_name='Endereço')),
                ('house_number', models.CharField(max_length=5, verbose_name='Número')),
                ('complement', models.CharField(max_length=100, verbose_name='Complemento')),
                ('district', models.CharField(max_length=30, verbose_name='Bairro')),
                ('zip_code', models.CharField(max_length=8, verbose_name='CEP')),
                ('city', models.CharField(max_length=30, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='estado')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstablishmentsContacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('cellphone', models.CharField(max_length=11, verbose_name='Celular com DDD')),
                ('telephone', models.CharField(blank=True, default='', max_length=8, verbose_name='Telefone')),
                ('email', models.CharField(blank=True, default='', max_length=50, verbose_name='E-mail')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstablishmentsOpeningHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('days', models.CharField(choices=[('Domingo', 'Domingo'), ('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Segunda a sexta', 'Segunda a sexta'), ('Segunda a sábado', 'Segunda a sábado'), ('Todos os dias', 'Todos os dias')], default='Escolha', max_length=16, verbose_name='Dias da semana')),
                ('opening_time', models.TimeField(verbose_name='Abertura')),
                ('closing_time', models.TimeField(verbose_name='Fechamento')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='author',
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='days',
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='establishmentsprofile',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='establishmentscategories',
            name='name',
            field=models.CharField(max_length=65, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='establishmentsprofile',
            name='Establishment',
            field=models.CharField(max_length=100, verbose_name='Nome do estabelecimento'),
        ),
        migrations.AlterField(
            model_name='establishmentsprofile',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Descreva seu estabelecimento'),
        ),
    ]
