# Generated by Django 4.1.2 on 2022-10-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0006_establishmentsadress_establishmentscontacts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishmentscategories',
            name='name',
        ),
        migrations.AddField(
            model_name='establishmentscategories',
            name='EstablishmentsCategory',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Categoria do estabelecimento'),
        ),
    ]
