# Generated by Django 4.1.2 on 2022-10-19 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0007_remove_establishmentscategories_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishmentsadress',
            options={'verbose_name_plural': 'Establishments Adress'},
        ),
        migrations.AlterModelOptions(
            name='establishmentscategories',
            options={'verbose_name_plural': 'Establishments Categories'},
        ),
        migrations.AlterModelOptions(
            name='establishmentscontacts',
            options={'verbose_name_plural': 'Establishments Contacts'},
        ),
        migrations.AlterModelOptions(
            name='establishmentsopeninghours',
            options={'verbose_name_plural': 'Establishments Opening Hours'},
        ),
        migrations.AlterModelOptions(
            name='establishmentsprofile',
            options={'verbose_name_plural': 'Establishments Profiles'},
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='establishmentsprofile',
            name='establishmentscategories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='establishments.establishmentscategories'),
        ),
    ]
