# Generated by Django 4.1.2 on 2022-10-19 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0008_alter_establishmentsadress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentsprofile',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='establishmentsprofile',
            name='establishmentscategories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='establishments.establishmentscategories', verbose_name='Categoria do estabelecimento'),
        ),
    ]
