# Generated by Django 4.1.2 on 2022-10-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0009_alter_establishmentsprofile_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishmentsprofile',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='cardapio-online-novo/covers/%Y/%m/%d/'),
        ),
    ]
