# Generated by Django 4.1.2 on 2022-11-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0011_alter_establishmentsprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentsprofile',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='establishments_images/%Y/%m/', verbose_name='Imagem'),
        ),
    ]
