# Generated by Django 4.1.3 on 2023-01-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0016_establishments_delete_establishmentsadress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishments',
            name='image',
        ),
    ]
