# Generated by Django 4.1.3 on 2023-01-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0017_remove_establishments_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establishments',
            old_name='Establishment',
            new_name='establishment',
        ),
        migrations.RenameField(
            model_name='establishments',
            old_name='EstablishmentsCategory',
            new_name='establishments_category',
        ),
    ]
