# Generated by Django 4.1.3 on 2023-01-06 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0018_rename_establishment_establishments_establishment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Establishments',
            new_name='Establishment',
        ),
    ]
