# Generated by Django 4.1.3 on 2023-01-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0021_alter_establishment_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='adress',
            field=models.CharField(max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='cellphone',
            field=models.CharField(max_length=11, verbose_name='Celular com DDD'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='complement',
            field=models.CharField(max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='district',
            field=models.CharField(max_length=30, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='house_number',
            field=models.CharField(max_length=5, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='zip_code',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
    ]
