# Generated by Django 4.1.3 on 2023-06-03 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0023_alter_establishment_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='cellphone',
            field=models.CharField(max_length=16, verbose_name='Celular com DDD'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='zip_code',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
    ]
