# Generated by Django 4.1.3 on 2023-01-13 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('image_item', models.ImageField(default='', upload_to='menus_images/%Y/%m/', verbose_name='Imagem do item')),
                ('item_name', models.CharField(blank=True, max_length=100, verbose_name='Nome do item')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('value', models.FloatField(blank=True, verbose_name='Valor')),
                ('item_description', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Menus',
                'ordering': ['-category'],
            },
        ),
    ]
