# Generated by Django 4.1.3 on 2023-01-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_remove_menu_created_at_remove_menu_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['category'], 'verbose_name_plural': 'Menus'},
        ),
    ]
