# Generated by Django 4.1.2 on 2022-10-19 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('enable', models.BooleanField(db_index=True, default=False, verbose_name='Habilitar botão de pedidos pelo Whatsapp')),
                ('OrdersPhone', models.CharField(max_length=11, verbose_name='Telefone que irá atender os pedidos')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
